### ISSUE TITLE
A list command to see all available cultures.

### ISSUE THREAD

**Issue by T3mp0st** [TownyAdvanced/TownyCultures#1]
Creating a command 
/C list or /c culture list 
this command would list cultures with their name, number of people, and number of towns. They could also be ranked on this list by these factors based on whatever the player would prefer in the config.

**Comment by Goosius1** [comment]
- I had a think about this, and although it is a reasonable suggestion, I think it would (perhaps surprisingly) detract from the feature.
- Consider the country of China. We may sometimes have considered the questions - "How big is China's army?", "How many tanks does it have?", "What is its foreign policy?". These are normal geopolitical questions. But the question of "How many people of Chinese heritage are there in the world?", is an "academic" or "scholarly" question.
- By adding a global list of culture-by-population to the TownyCultures plugin, I'm quite certain that this academic question would transform in many player's minds into an "achievement ranking", where some players would want to "achieve" by being in the "top" culture, others would be "recruited" into a culture purely to get the numbers up, others would be reluctant to change culture lest they "drop" in the rankings, and cultural "emperors" would emerge with their job being to direct a particular culture to the "top".
- One example of this would be a new player logging into a server, seeing the top culture was Chinese, and then decided that yes, the best course of action is to be Chinese......
- This would all be quite unnatural. Instead, I would like the feature to remain the home of "social" players, with "achievement" players being given no extra incentive (like a ranked list) to use it for achievement purposes. Thus for now, I'm not in favour of a global ranked list. 
- However, the local arrangement of cultures is certainly important for the normal geopolitical concept of "nationalism", thus I will try to add a `%culture%` placeholders to the Towny-Dynmap. 
- A different list of this nature, which I would support, is a 'nation-based' list, where you could get a list of all component cultures in a particular nation. This would be a useful geopolitical tool to assess the loyalties of a particular friend or foe. Feel free to create a new ticket for that.
