### ISSUE TITLE
Suggestion: List of Cultures and the ability to delete/remove cultures!

### ISSUE THREAD

**Issue by 0xBit-MC** [TownyAdvanced/TownyCultures#17]
Simply have a command that lists all available cultures listed by popularity. Perhaps this can expand into the idea of seeing which culture is the most popular on the server.

Secondly, allow for administrators to delete/remove cultures from the server, because people are making inappropriate cultures is a bit hard to track on a town by town basis.

**Comment by LlmDl** [comment]
This sort of falls into the same as this [ticket](https://github.com/TownyAdvanced/TownyCultures/issues/1). The main argument against it, is that it would end up causing a trend that consolidates the power in the dominant cultures.

I'm all for seeing a raw list of cultures with no order to them (or maybe order them only for admins,) and the ability to remove offensive ones.

**Comment by MilesBHuff** [comment]
A randomized list of cultures could be doable.
Worth mentioning, though, that the recent addition of culture names to the world map mean that people can already click around and get an idea of which cultures are the most powerful.
