### ISSUE TITLE
Suggestion: Add Placeholder for Culture Name

### ISSUE THREAD

**Issue by Caleston** [TownyAdvanced/TownyCultures#22]
Adding a %-% Placeholder for Culture Name would be fantastic, as this would let us display it on Dynmap-Towny and elsewhere.
Havent found any other methods of displaying it automatically.

**Comment by LlmDl** [comment]
For the dynmap you can already use %culture% in the infowindow line of the dynmap-towny config.

**Comment by LlmDl** [comment]
Actually, that might not be in the last release, and will instead be part of the next release.

**Comment by MilesBHuff** [comment]
Is there an ETA for 1.2.0?

**Comment by LlmDl** [comment]
Should be out this week along with a bunch of other releases.
