### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/TownyCultures#27]
**To Reproduce**
1. /c set 123
2. error. see photo down

**Screenshots**
![image](https://user-images.githubusercontent.com/73141732/136122000-a902ba6d-67d7-433e-8d5c-1b7408a0d7c5.png)

**Versions (please complete the following information):**
 - Towny: 0.97.2.0
 - TownyCultures: 1.2.0
 - Spigot/Paper: paper 1.17.1

**Files**
Startup log: ok
TownyCultures config: default
Townyperms.yml: default

**Comment by LlmDl** [comment]
Whats the name of the player running the command?

**Comment by LlmDl** [comment]
Nevermind that. Should have it fixed.
