### ISSUE TITLE
First letter is small even if the culture has a big letter at first. (Infowindow)

### ISSUE THREAD

**Issue by noisereactz1** [TownyAdvanced/TownyCultures#29]
When i go to my dynmap and look on the infowindow the culture i set is shown with a small letter at the beginning even if the culture has a big letter at first.

Versions:
 - Towny: newest
 - TownyCultures: newest
 - Spigot/Paper: 1.16.5

**Comment by noisereactz1** [comment]
ok no answer, fine......

**Comment by noisereactz1** [comment]
the code doesnt fix my problem. i need a new jar or do i not?

**Comment by LlmDl** [comment]
https://cdn.discordapp.com/attachments/669247087329673228/906283811606786148/TownyCultures-1.2.3.jar should solve it.

**Comment by noisereactz1** [comment]
thank you! 1.2.3 fixed it <3
