### ISSUE TITLE
Please change the 'cc' command to 'culturechat'

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/TownyCultures#32]
Please change the 'cc' command to 'culturechat', and the alias for it is 'cc', because I have a plugin that conflicts with 'cc', cultures overlap the command from another plugin, and if it was like I said, then I would just take the plugin.yml and replace the alias, there would be no problem

**Comment by LlmDl** [comment]
You can use the commands.yml in your server folder to choose what commands will be used when cc is typed.
