### ISSUE TITLE
Suggestion: Add Religions to TownyCultures

### ISSUE THREAD

**Issue by rogo159** [TownyAdvanced/TownyCultures#39]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Please add a religion section to TownyCultures so we can make them more clear in our server. It is very beneficial to have both a cultural and religious category for towns/nations.

**Describe alternatives you've considered**
Other religion plugins, but none are integrated into Towny and are not as accessible, making it more complicated.

**Additional context**
None.

**Comment by LlmDl** [comment]
Duplicate of #23
