### ISSUE TITLE
Suggestion: Nation screen - Prevent cultures being shown twice due to casing issues

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/TownyCultures#8]
**Is your feature request related to a problem? Please describe.**
- Currently on the nation culture demographics list, I believe casing will separate cultures e.g. you could have "Russian: 30%, russian: 2%....."

**Describe the solution you'd like**
- Fix it so that you only get one version shown
- I believe a reasonable option might be to format it when it is set by the mayor ---- so that each separate word is change if required, to start with an uppercase letter and have all others letters lowercase.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LlmDl** [comment]
Probably best to store all cultures lower cased and then just capitalize them when displaying them. Then you don't have that guy that wants his BEST CULTURE all in caps.
